### ISSUE TITLE
Parse Hive External Table DDL with Partitions 

### ISSUE THREAD

**Issue by nitin-kakkar** [xnuinside/simple-ddl-parser#19]
I have below hive DDL which i need to parse but it is not working. @xnuinside - could you please help
```
CREATE EXTERNAL TABLE IF NOT EXISTS database.table_name
(
    day_long_nm     string,
    calendar_dt     date,
    source_batch_id string,
    field_qty       decimal(10, 0),
    field_bool      boolean,
    field_float     float,
    create_tmst     timestamp,
    field_double    double,
    field_long      bigint
) PARTITIONED BY (batch_id int) STORED AS PARQUET LOCATION 's3://datalake/table_name/v1'
```

**Comment by xnuinside** [comment]
@nitin-kakkar , hello. External - keyword was nt added yet & partitioned by also. I will return from vacation on 31 March and will continue on library. I will add support to this statements.

**Comment by nitin-kakkar** [comment]
@xnuinside - thanks!!

**Comment by nitin-kakkar** [comment]
thank you so much @xnuinside  -
are complex data types also supported - 
column_abc            ARRAY<struct<colx:string,coly:string>>
looking for following output
```
{
                    "name": "column_abc",
                    "type": "ARRAY<struct<colx:string,coly:string>>",
                    "size": None,
                    "references": None,
                    "unique": False,
                    "nullable": True,
                    "default": None,
                    "check": None,
 }
```

**Comment by nitin-kakkar** [comment]
@xnuinside - This example is noot working.. multiple partition columns 
`from simple_ddl_parser import DDLParser

ddl = """
CREATE EXTERNAL TABLE IF NOT EXISTS database.table_name
(
    day_long_nm     string,
    calendar_dt     date
) PARTITIONED BY (batch_id int,batch_nm string) STORED AS PARQUET LOCATION 's3://datalake/table_name/v1'

"""

result = DDLParser(ddl).run(output_mode="hql")
print(result)
`

**Comment by xnuinside** [comment]
@nitin-kakkar, oops :) sorry, multiple partition columns - fixed in  https://pypi.org/project/simple-ddl-parser/0.8.0a1/ . test with output here https://github.com/xnuinside/simple-ddl-parser/pull/21/files

**Comment by xnuinside** [comment]
@nitin-kakkar  I released 0.8.0 with fixes for multiple partition columns + also added https://github.com/xnuinside/simple-ddl-parser/pull/22 HQL ROW FORMAT statement, FIELDS TERMINATED BY statement, COLLECTION ITEMS TERMINATED BY statement, MAP KEYS TERMINATED BY statement

**Comment by nitin-kakkar** [comment]
@xnuinside - Thanks!! . multiple partitioned column is working fine. did you also add complex data type support. https://github.com/xnuinside/simple-ddl-parser/issues/19#issuecomment-811494765 - is still not working
Thanks again for a quick turnaround.

**Comment by xnuinside** [comment]
@nitin-kakkar, not supported yet, I will add it in next update

**Comment by xnuinside** [comment]
@nitin-kakkar, added in 0.8.1, please test, samples here - https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L974 & https://github.com/xnuinside/simple-ddl-parser/blob/main/tests/test_hql_output_mode.py#L1021

**Comment by nitin-kakkar** [comment]
@xnuinside - complex types are working fine now.. just a small issue - whitespaces are getting added in types
for column - abc_groups ARRAY<struct<some_field_one:string,some_field_two:string>>
output - you will notice whitespaces - "ARRAY <struct <" in key type
```
{
        'name': 'abc_groups',
        'type': 'ARRAY <struct <some_field_one:string,some_field_two:string>>',
        'size': None,
        'references': None,
        'unique': False,
        'nullable': True,
        'default': None,
        'check': None
      },
```

**Comment by xnuinside** [comment]
@nitin-kakkar, yes, I know about it, not sure how to fix this issue faster, I will try to solve it in next releases, but not sure how to do this easy way. It's because of structure parsing.

**Comment by nitin-kakkar** [comment]
@xnuinside - no worries .. thanks again for quick turnaround... you can close the issue.. 

> @nitin-kakkar, yes, I know about it, not sure how to fix this issue faster, I will try to solve it in next releases, but not sure how to do this easy way. It's because of structure parsing.

**Comment by xnuinside** [comment]
@nitin-kakkar, to understand that this is a structure defining in type, I need get < and > symbols as separate tokens, but to do this I need 'cut' them from string, so in pre-parsing step I do from  `ARRAY<struct<some_field_one:string,some_field_two:string>>` `ARRAY < struct < some_field_one:string,some_field_two:string > > `
I can just remove spaces at the end, but I don't know was them in place at the start or no. If I will figure out how to extract this type without adding additional ' ' - I will fix it.
